### PR TITLE
Add Books Library Inventory Script By Mohammad Ballal

### PR DESCRIPTION
**Pull request by Mvamd12**
Hello i'm just added a python file contain a script manages an inventory of books.

### CODE REVIEW

**Comment by FaresAbuIram** [comment]
Everything is good, but in real work, we always need to add a good description of what we did :).

Also, can you please comment in your file for steps as the example file FIRST-NAME_LAST-NAME.py. Example:
# Step 1: Initialize Book Inventory ....

**Comment by Mvamd12** [comment]
> Everything is good, but in real work, we always need to add a good description of what we did :).
> 
> Also, can you please comment in your file for steps as the example file FIRST-NAME_LAST-NAME.py. Example: `# Step 1: Initialize Book Inventory ....`

Thanks, 
did you mean the commit description by the first part of your comment ?

**Comment by FaresAbuIram** [comment]
I mean the description part here.

Screenshot 2024-08-12 at 16 21 34

**Comment by Mohammed-samaheen** [comment]
LGTM, nice work.

**Review by Mohammed-samaheen — APPROVED** [review]

**Review by FaresAbuIram — CHANGES_REQUESTED** [review]

**Review by FaresAbuIram — APPROVED** [review]
When you only have two quotes, it doesn't matter whether you use single quotes or double quotes. For example:

`book['author'] is the same as book["author"].`

However, when you have more than two quotes, it's important to make the outermost quotes consistent. For example:

`f"{book['title']} is related to {book['tags'][0]}"`


Everything is good now. Well done!

**Comment by FaresAbuIram** [comment]
please merge it

**Pull request merged**
